services:

  mysql:
    image: mysql:8.4
    container_name: leap-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leap_db
      MYSQL_USER: leap_user
      MYSQL_PASSWORD: leap_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: leap-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: