spring.application.name=project_leap_25cc062_vignesh

spring.datasource.url=jdbc:mysql://localhost:3307/leap_db
spring.datasource.username=leap_user
spring.datasource.password=leap_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8086